-- ============================================================
-- ESQUEMA DE REFERENCIA — volcado del panel de Supabase el 17/09/2026
--
-- NO ES PARA EJECUTAR. Es la foto de las tablas tal y como están en producción,
-- guardada porque las tablas troncales (perfiles, leads, captaciones, demandas,
-- propiedades_demanda, app_settings, scraper_zonas, historial_cambios) se crearon
-- desde el panel y no tienen CREATE TABLE en ninguna migración de este repo.
--
-- QUÉ FALTA AQUÍ: vistas (contactos, v_mi_dia, mercado_zonas_stats,
-- perfiles_con_email), funciones, triggers, índices y políticas de RLS. Las
-- funciones y triggers sí están en migrations/; las políticas antiguas creadas
-- desde el panel, no.
--
-- El orden de las tablas y las restricciones puede no ser válido para ejecutar.
-- ============================================================

CREATE TABLE public.perfiles (
  id uuid NOT NULL,
  nombre text NOT NULL,
  apellidos text,
  rol text DEFAULT 'Agente'::text,
  avatar_url text,
  telefono text,
  permisos jsonb DEFAULT '{"leads": true, "mensajes": true, "captaciones": true}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  usuario text UNIQUE,
  onboarding_done boolean NOT NULL DEFAULT false,
  disponible boolean NOT NULL DEFAULT true,
  orden_reparto integer,
  zonas ARRAY NOT NULL DEFAULT '{}'::text[],
  especialidades ARRAY NOT NULL DEFAULT '{}'::text[],
  CONSTRAINT perfiles_pkey PRIMARY KEY (id),
  CONSTRAINT perfiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.leads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nombre text NOT NULL,
  apellidos text,
  email text,
  telefono text,
  fuente text DEFAULT 'Web'::text,
  estado text DEFAULT 'Nuevo'::text CHECK (estado = ANY (ARRAY['Nuevo'::text, 'Contactado'::text, 'Interesado'::text, 'Propuesta'::text, 'Negociacion'::text, 'Ganado'::text, 'Perdido'::text])),
  notas text,
  fecha_creacion timestamp with time zone DEFAULT now(),
  captado_por uuid,
  captacion_id bigint,
  wa_jid text,
  asignado_en timestamp with time zone,
  asignado_por uuid,
  asignacion_motivo text,
  rechazado_por ARRAY NOT NULL DEFAULT '{}'::uuid[],
  motivo_perdida text,
  perdido_en timestamp with time zone,
  telefono_norm text,
  email_norm text,
  duplicado_de uuid,
  external_id text,
  canal text,
  propiedad_ref text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_content text,
  utm_term text,
  landing_url text,
  consent_rgpd boolean,
  consent_en timestamp with time zone,
  recibido_en timestamp with time zone,
  atendido_en timestamp with time zone,
  atendido_por uuid,
  proximo_toque timestamp with time zone,
  proximo_motivo text,
  contacto_desde timestamp with time zone,
  agente_id uuid,
  CONSTRAINT leads_pkey PRIMARY KEY (id),
  CONSTRAINT leads_atendido_por_fkey FOREIGN KEY (atendido_por) REFERENCES public.perfiles(id),
  CONSTRAINT leads_captado_por_fkey FOREIGN KEY (captado_por) REFERENCES public.perfiles(id),
  CONSTRAINT leads_asignado_por_fkey FOREIGN KEY (asignado_por) REFERENCES public.perfiles(id),
  CONSTRAINT leads_duplicado_de_fkey FOREIGN KEY (duplicado_de) REFERENCES public.leads(id),
  CONSTRAINT leads_agente_id_fkey FOREIGN KEY (agente_id) REFERENCES public.perfiles(id)
);
CREATE TABLE public.captaciones (
  id bigint NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  nombre text,
  telefono text,
  precio numeric,
  precio_m2 numeric,
  barrio text,
  calle text,
  metros integer,
  habitaciones integer,
  banos integer,
  planta text,
  tiene_ascensor boolean,
  estado text,
  descripcion text,
  url text,
  raw_data jsonb,
  activo boolean DEFAULT true,
  imagen_url text,
  imagenes ARRAY,
  agente_id uuid,
  fecha_agenda timestamp with time zone,
  recordatorio_fecha timestamp with time zone,
  notas_agenda text,
  estado_agenda text DEFAULT 'pendiente'::text CHECK (estado_agenda = ANY (ARRAY['pendiente'::text, 'completado'::text, 'cancelado'::text])),
  estado_crm text NOT NULL DEFAULT 'Nuevo'::text CHECK (estado_crm = ANY (ARRAY['Nuevo'::text, 'Contactado'::text, 'Interesado'::text, 'Propuesta'::text, 'Negociacion'::text, 'Ganado'::text, 'Perdido'::text])),
  estado_whatsapp text,
  visto_en timestamp with time zone,
  contacto_lock_en timestamp with time zone,
  ultimo_contacto_en timestamp with time zone,
  fotos_procesadas boolean NOT NULL DEFAULT false,
  precio_anterior numeric,
  precio_actualizado_en timestamp with time zone,
  asignado_en timestamp with time zone,
  asignado_por uuid,
  asignacion_motivo text,
  rechazado_por ARRAY NOT NULL DEFAULT '{}'::uuid[],
  atendido_en timestamp with time zone,
  atendido_por uuid,
  proximo_toque timestamp with time zone,
  proximo_motivo text,
  prospecto_id uuid,
  senal text,
  senal_en timestamp with time zone,
  CONSTRAINT captaciones_pkey PRIMARY KEY (id),
  CONSTRAINT captaciones_atendido_por_fkey FOREIGN KEY (atendido_por) REFERENCES public.perfiles(id),
  CONSTRAINT captaciones_agente_id_fkey FOREIGN KEY (agente_id) REFERENCES public.perfiles(id),
  CONSTRAINT captaciones_prospecto_id_fkey FOREIGN KEY (prospecto_id) REFERENCES public.prospectos(id),
  CONSTRAINT captaciones_asignado_por_fkey FOREIGN KEY (asignado_por) REFERENCES public.perfiles(id)
);
CREATE TABLE public.historial_cambios (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  captacion_id bigint,
  fecha timestamp with time zone DEFAULT now(),
  campo text,
  valor_anterior text,
  valor_nuevo text,
  hecho_por uuid,
  lead_id uuid,
  tipo_entidad text DEFAULT 'captacion'::text,
  CONSTRAINT historial_cambios_pkey PRIMARY KEY (id),
  CONSTRAINT historial_cambios_captacion_id_fkey FOREIGN KEY (captacion_id) REFERENCES public.captaciones(id),
  CONSTRAINT historial_cambios_hecho_por_fkey FOREIGN KEY (hecho_por) REFERENCES public.perfiles(id),
  CONSTRAINT historial_cambios_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(id)
);
CREATE TABLE public.app_settings (
  key text NOT NULL,
  value jsonb,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT app_settings_pkey PRIMARY KEY (key)
);
CREATE TABLE public.scraper_zonas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nombre text NOT NULL,
  tipo text NOT NULL CHECK (tipo = ANY (ARRAY['nombre'::text, 'zona'::text, 'url'::text])),
  url text NOT NULL,
  search_name text,
  coords jsonb,
  activa boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  ultima_ejecucion timestamp with time zone,
  ultimo_resultado integer,
  ventana_horas integer NOT NULL DEFAULT 24,
  operacion text NOT NULL DEFAULT 'venta'::text CHECK (operacion = ANY (ARRAY['venta'::text, 'alquiler'::text])),
  tipo_inmueble text NOT NULL DEFAULT 'viviendas'::text CHECK (tipo_inmueble = ANY (ARRAY['viviendas'::text, 'locales'::text, 'garajes'::text, 'oficinas'::text, 'terrenos'::text, 'trasteros'::text])),
  prioridad integer NOT NULL DEFAULT 100,
  CONSTRAINT scraper_zonas_pkey PRIMARY KEY (id)
);
CREATE TABLE public.propiedades_demanda (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ref text NOT NULL UNIQUE,
  tipo text,
  accion text,
  ciudad text,
  zona text,
  cp text,
  precio_alquiler integer NOT NULL DEFAULT 0,
  precio_venta integer NOT NULL DEFAULT 0,
  habitaciones integer NOT NULL DEFAULT 0,
  banyos integer NOT NULL DEFAULT 0,
  m_construidos numeric NOT NULL DEFAULT 0,
  titulo text,
  descripcion text,
  extras jsonb NOT NULL DEFAULT '[]'::jsonb,
  activo boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT propiedades_demanda_pkey PRIMARY KEY (id)
);
CREATE TABLE public.demandas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  propiedad_id uuid NOT NULL,
  nombre text,
  telefono text,
  email text,
  fuente text NOT NULL DEFAULT 'Otros'::text,
  mensaje text,
  estado text NOT NULL DEFAULT 'Nuevo'::text CHECK (estado = ANY (ARRAY['Nuevo'::text, 'Contactado'::text, 'Cualificado'::text, 'Descartado'::text])),
  notas text,
  wa_jid text,
  datos_cualificacion jsonb,
  visto boolean NOT NULL DEFAULT false,
  fecha_creacion timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT demandas_pkey PRIMARY KEY (id),
  CONSTRAINT demandas_propiedad_id_fkey FOREIGN KEY (propiedad_id) REFERENCES public.propiedades_demanda(id)
);
CREATE TABLE public.mercado_inmuebles (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  idealista_id text NOT NULL UNIQUE,
  operacion text DEFAULT 'venta'::text,
  tipo text,
  codbarrio text,
  barrio text,
  lat double precision,
  lng double precision,
  precio numeric,
  metros numeric,
  precio_m2 numeric DEFAULT
CASE
    WHEN (metros > (0)::numeric) THEN round((precio / metros), 2)
    ELSE NULL::numeric
END,
  habitaciones integer,
  banos integer,
  planta text,
  ascensor boolean,
  estado_conservacion text,
  anunciante text,
  agencia_nombre text,
  activo boolean DEFAULT true,
  fecha_primera_vista timestamp with time zone DEFAULT now(),
  fecha_ultima_vista timestamp with time zone DEFAULT now(),
  fecha_baja timestamp with time zone,
  precio_baja numeric,
  raw jsonb,
  imagen_url text,
  usable_area numeric,
  exterior boolean,
  energia text,
  energia_kwh numeric,
  piscina boolean,
  jardin boolean,
  trastero boolean,
  parking boolean,
  terraza boolean,
  aire boolean,
  gastos_comunidad numeric,
  obra_nueva boolean,
  caracteristicas jsonb,
  tipo_detallado text,
  CONSTRAINT mercado_inmuebles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.valoraciones (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  creada_en timestamp with time zone DEFAULT now(),
  creada_por uuid,
  direccion text,
  codbarrio text,
  barrio text,
  lat double precision,
  lng double precision,
  metros numeric,
  habitaciones integer,
  operacion text DEFAULT 'venta'::text,
  precio_m2_zona numeric,
  valor_estimado numeric,
  valor_min numeric,
  valor_max numeric,
  muestra integer,
  notas text,
  comparables jsonb,
  CONSTRAINT valoraciones_pkey PRIMARY KEY (id),
  CONSTRAINT valoraciones_creada_por_fkey FOREIGN KEY (creada_por) REFERENCES public.perfiles(id)
);
CREATE TABLE public.mercado_precio_historial (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  idealista_id text,
  precio_anterior numeric,
  precio_nuevo numeric,
  delta numeric,
  pct numeric,
  direccion text,
  fecha timestamp with time zone DEFAULT now(),
  CONSTRAINT mercado_precio_historial_pkey PRIMARY KEY (id)
);
CREATE TABLE public.agenda (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  titulo text NOT NULL,
  descripcion text,
  tipo text NOT NULL DEFAULT 'cita'::text,
  fecha timestamp with time zone NOT NULL,
  todo_el_dia boolean NOT NULL DEFAULT false,
  agente_id uuid,
  creado_por uuid,
  completado boolean NOT NULL DEFAULT false,
  captacion_id bigint,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  lead_id uuid,
  prospecto_id uuid,
  CONSTRAINT agenda_pkey PRIMARY KEY (id),
  CONSTRAINT agenda_agente_id_fkey FOREIGN KEY (agente_id) REFERENCES public.perfiles(id),
  CONSTRAINT agenda_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES public.perfiles(id),
  CONSTRAINT agenda_lead_fk FOREIGN KEY (lead_id) REFERENCES public.leads(id),
  CONSTRAINT agenda_captacion_fk FOREIGN KEY (captacion_id) REFERENCES public.captaciones(id),
  CONSTRAINT agenda_prospecto_id_fkey FOREIGN KEY (prospecto_id) REFERENCES public.prospectos(id)
);
CREATE TABLE public.catalogos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tipo text NOT NULL,
  valor text NOT NULL,
  nombre text NOT NULL,
  color text,
  orden integer NOT NULL DEFAULT 100,
  activo boolean NOT NULL DEFAULT true,
  sistema boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT catalogos_pkey PRIMARY KEY (id)
);
CREATE TABLE public.lead_etiquetas (
  lead_id uuid NOT NULL,
  etiqueta_id uuid NOT NULL,
  puesta_por uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT lead_etiquetas_pkey PRIMARY KEY (lead_id, etiqueta_id),
  CONSTRAINT lead_etiquetas_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(id),
  CONSTRAINT lead_etiquetas_etiqueta_id_fkey FOREIGN KEY (etiqueta_id) REFERENCES public.catalogos(id),
  CONSTRAINT lead_etiquetas_puesta_por_fkey FOREIGN KEY (puesta_por) REFERENCES public.perfiles(id)
);
CREATE TABLE public.interacciones (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lead_id uuid,
  captacion_id bigint,
  tipo text NOT NULL,
  direccion text NOT NULL DEFAULT 'interna'::text CHECK (direccion = ANY (ARRAY['entrante'::text, 'saliente'::text, 'interna'::text])),
  canal text,
  resumen text NOT NULL,
  detalle text,
  agente_id uuid,
  automatica boolean NOT NULL DEFAULT false,
  ocurrida_en timestamp with time zone NOT NULL DEFAULT now(),
  meta jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  prospecto_id uuid,
  CONSTRAINT interacciones_pkey PRIMARY KEY (id),
  CONSTRAINT interacciones_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(id),
  CONSTRAINT interacciones_captacion_id_fkey FOREIGN KEY (captacion_id) REFERENCES public.captaciones(id),
  CONSTRAINT interacciones_agente_id_fkey FOREIGN KEY (agente_id) REFERENCES public.perfiles(id),
  CONSTRAINT interacciones_prospecto_id_fkey FOREIGN KEY (prospecto_id) REFERENCES public.prospectos(id)
);
CREATE TABLE public.prospectos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  contacto_id uuid NOT NULL,
  captacion_id bigint,
  captado_por uuid,
  agente_id uuid,
  creado_por uuid,
  estado text NOT NULL DEFAULT 'Nuevo'::text,
  motivo_perdida text,
  perdido_en timestamp with time zone,
  direccion text,
  barrio text,
  ciudad text NOT NULL DEFAULT 'Valencia'::text,
  tipo_inmueble text,
  operacion text,
  precio numeric,
  precio_salida numeric,
  metros integer,
  habitaciones integer,
  banos integer,
  planta text,
  tiene_ascensor boolean,
  estado_inmueble text,
  descripcion text,
  imagenes ARRAY,
  url_anuncio text,
  exclusiva boolean,
  honorarios_pct numeric,
  atendido_en timestamp with time zone,
  atendido_por uuid,
  proximo_toque timestamp with time zone,
  proximo_motivo text,
  propiedad_ref text,
  captada_en timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT prospectos_pkey PRIMARY KEY (id),
  CONSTRAINT prospectos_contacto_id_fkey FOREIGN KEY (contacto_id) REFERENCES public.leads(id),
  CONSTRAINT prospectos_captacion_id_fkey FOREIGN KEY (captacion_id) REFERENCES public.captaciones(id),
  CONSTRAINT prospectos_captado_por_fkey FOREIGN KEY (captado_por) REFERENCES public.perfiles(id),
  CONSTRAINT prospectos_agente_id_fkey FOREIGN KEY (agente_id) REFERENCES public.perfiles(id),
  CONSTRAINT prospectos_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES public.perfiles(id),
  CONSTRAINT prospectos_atendido_por_fkey FOREIGN KEY (atendido_por) REFERENCES public.perfiles(id)
);
