-- ============================================================
-- SANDBOX · PASO 1: exportar la ESTRUCTURA de producción
--
-- QUÉ ES. Una consulta de SOLO LECTURA para ejecutar en el proyecto de
-- PRODUCCIÓN. No escribe nada, no cambia nada y NO saca datos: sólo la
-- definición de tablas, funciones, vistas, triggers, índices, políticas de
-- RLS, permisos, tiempo real y buckets. Con eso se levanta `crm-sandbox`
-- idéntico por dentro, pero vacío.
--
-- POR QUÉ HACE FALTA. Las tablas troncales (perfiles, leads, captaciones,
-- demandas...) se crearon desde el panel y no están en ninguna migración, y
-- muchas políticas tampoco. `schema-referencia.sql` sólo trae las tablas. Aplicar
-- las 38 migraciones sobre un proyecto vacío no reproduce producción.
--
-- CÓMO.
--   1. SQL Editor del proyecto de PRODUCCIÓN → pegar todo → Run.
--   2. Sale una tabla de unas 17 filas (una por sección).
--   3. Botón de exportar/descargar resultados → CSV.
--   4. Guardarlo como  crm/supabase/sandbox/estructura-produccion.csv
--
-- Cada sección lleva `objetos` (cuántas piezas trae) para comprobar al leer el
-- CSV que no se ha cortado nada. Las piezas van separadas por la línea
-- `-- @@FIN@@` porque las funciones llevan `;` dentro y no se puede partir por ahí.
-- ============================================================

WITH
fin AS (SELECT E'\n-- @@FIN@@\n' AS s),

ext AS (
  SELECT format('CREATE EXTENSION IF NOT EXISTS %I WITH SCHEMA %I;', e.extname, n.nspname) AS q, e.extname AS k
    FROM pg_extension e JOIN pg_namespace n ON n.oid = e.extnamespace
   WHERE e.extname <> 'plpgsql'
),

tipos AS (
  SELECT format('CREATE TYPE public.%I AS ENUM (%s);', t.typname,
                string_agg(quote_literal(e.enumlabel), ', ' ORDER BY e.enumsortorder)) AS q, t.typname::text AS k
    FROM pg_type t JOIN pg_enum e ON e.enumtypid = t.oid
   WHERE t.typnamespace = 'public'::regnamespace
   GROUP BY t.typname
),

secuencias AS (
  SELECT format('CREATE SEQUENCE IF NOT EXISTS public.%I;', c.relname) AS q, c.relname::text AS k
    FROM pg_class c
   WHERE c.relnamespace = 'public'::regnamespace AND c.relkind = 'S'
     AND NOT EXISTS (SELECT 1 FROM pg_depend d WHERE d.objid = c.oid AND d.deptype = 'i')
),

tablas AS (
  SELECT format('CREATE TABLE IF NOT EXISTS public.%I (%s);', c.relname,
           string_agg(
             format('%I %s%s%s%s', a.attname, format_type(a.atttypid, a.atttypmod),
               CASE a.attidentity WHEN 'a' THEN ' GENERATED ALWAYS AS IDENTITY'
                                  WHEN 'd' THEN ' GENERATED BY DEFAULT AS IDENTITY' ELSE '' END,
               CASE WHEN a.attgenerated = 's' THEN ' GENERATED ALWAYS AS (' || pg_get_expr(d.adbin, d.adrelid) || ') STORED'
                    WHEN d.adbin IS NOT NULL   THEN ' DEFAULT ' || pg_get_expr(d.adbin, d.adrelid)
                    ELSE '' END,
               CASE WHEN a.attnotnull THEN ' NOT NULL' ELSE '' END),
             ', ' ORDER BY a.attnum)) AS q, c.relname::text AS k
    FROM pg_class c
    JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum > 0 AND NOT a.attisdropped
    LEFT JOIN pg_attrdef d ON d.adrelid = c.oid AND d.adnum = a.attnum
   WHERE c.relnamespace = 'public'::regnamespace AND c.relkind IN ('r', 'p')
   GROUP BY c.relname
),

restricciones AS (
  SELECT format('ALTER TABLE public.%I ADD CONSTRAINT %I %s;', c.relname, co.conname, pg_get_constraintdef(co.oid)) AS q,
         c.relname || '.' || co.conname AS k
    FROM pg_constraint co JOIN pg_class c ON c.oid = co.conrelid
   WHERE c.relnamespace = 'public'::regnamespace AND co.contype IN ('p', 'u', 'c', 'x')
),

claves_ajenas AS (
  SELECT format('ALTER TABLE public.%I ADD CONSTRAINT %I %s;', c.relname, co.conname, pg_get_constraintdef(co.oid)) AS q,
         c.relname || '.' || co.conname AS k
    FROM pg_constraint co JOIN pg_class c ON c.oid = co.conrelid
   WHERE c.relnamespace = 'public'::regnamespace AND co.contype = 'f'
),

funciones AS (
  SELECT pg_get_functiondef(p.oid) || ';' AS q, p.oid::regprocedure::text AS k
    FROM pg_proc p
   WHERE p.pronamespace = 'public'::regnamespace AND p.prokind IN ('f', 'p')
     AND NOT EXISTS (SELECT 1 FROM pg_depend d WHERE d.objid = p.oid AND d.deptype = 'e')
),

vistas AS (
  SELECT format('CREATE OR REPLACE %sVIEW public.%I%s AS %s',
           CASE WHEN c.relkind = 'm' THEN 'MATERIALIZED ' ELSE '' END,
           c.relname,
           CASE WHEN c.reloptions IS NOT NULL THEN ' WITH (' || array_to_string(c.reloptions, ', ') || ')' ELSE '' END,
           pg_get_viewdef(c.oid, true)) AS q, c.relname::text AS k
    FROM pg_class c
   WHERE c.relnamespace = 'public'::regnamespace AND c.relkind IN ('v', 'm')
),

indices AS (
  SELECT regexp_replace(pg_get_indexdef(i.indexrelid), '^CREATE (UNIQUE )?INDEX ', 'CREATE \1INDEX IF NOT EXISTS ') || ';' AS q,
         i.indexrelid::regclass::text AS k
    FROM pg_index i JOIN pg_class c ON c.oid = i.indrelid
   WHERE c.relnamespace = 'public'::regnamespace
     AND NOT EXISTS (SELECT 1 FROM pg_constraint co WHERE co.conindid = i.indexrelid)
),

disparadores AS (
  SELECT pg_get_triggerdef(t.oid, true) || ';' AS q, c.relname || '.' || t.tgname AS k
    FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid
   WHERE NOT t.tgisinternal
     AND (c.relnamespace = 'public'::regnamespace OR t.tgrelid = 'auth.users'::regclass)
),

rls AS (
  SELECT format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', c.relname)
         || CASE WHEN c.relforcerowsecurity THEN format(E'\nALTER TABLE public.%I FORCE ROW LEVEL SECURITY;', c.relname) ELSE '' END AS q,
         c.relname::text AS k
    FROM pg_class c
   WHERE c.relnamespace = 'public'::regnamespace AND c.relkind IN ('r', 'p') AND c.relrowsecurity
),

politicas AS (
  SELECT format('CREATE POLICY %I ON %I.%I AS %s FOR %s TO %s%s%s;',
           p.policyname, p.schemaname, p.tablename, p.permissive, p.cmd,
           array_to_string(p.roles, ', '),
           CASE WHEN p.qual IS NOT NULL THEN ' USING (' || p.qual || ')' ELSE '' END,
           CASE WHEN p.with_check IS NOT NULL THEN ' WITH CHECK (' || p.with_check || ')' ELSE '' END) AS q,
         p.schemaname || '.' || p.tablename || '.' || p.policyname AS k
    FROM pg_policies p
   WHERE p.schemaname IN ('public', 'storage')
),

permisos_tablas AS (
  SELECT format('REVOKE ALL ON TABLE public.%I FROM anon, authenticated, service_role;', c.relname)
         || coalesce(E'\n' || (
              SELECT string_agg(format('GRANT %s ON TABLE public.%I TO %I;', g.privs, c.relname, g.rolname), E'\n')
                FROM (SELECT r.rolname, string_agg(DISTINCT x.privilege_type, ', ') AS privs
                        FROM aclexplode(c.relacl) x JOIN pg_roles r ON r.oid = x.grantee
                       WHERE r.rolname IN ('anon', 'authenticated', 'service_role')
                       GROUP BY r.rolname) g), '') AS q,
         c.relname::text AS k
    FROM pg_class c
   WHERE c.relnamespace = 'public'::regnamespace AND c.relkind IN ('r', 'p', 'v', 'm') AND c.relacl IS NOT NULL
),

permisos_funciones AS (
  SELECT format('REVOKE ALL ON FUNCTION %s FROM PUBLIC, anon, authenticated, service_role;', p.oid::regprocedure)
         || coalesce(E'\n' || (
              SELECT string_agg(format('GRANT EXECUTE ON FUNCTION %s TO %s;', p.oid::regprocedure,
                                       CASE WHEN x.grantee = 0 THEN 'PUBLIC' ELSE quote_ident(r.rolname) END), E'\n')
                FROM aclexplode(p.proacl) x LEFT JOIN pg_roles r ON r.oid = x.grantee
               WHERE x.privilege_type = 'EXECUTE'
                 AND (x.grantee = 0 OR r.rolname IN ('anon', 'authenticated', 'service_role'))), '') AS q,
         p.oid::regprocedure::text AS k
    FROM pg_proc p
   WHERE p.pronamespace = 'public'::regnamespace AND p.proacl IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_depend d WHERE d.objid = p.oid AND d.deptype = 'e')
),

tiempo_real AS (
  SELECT format('ALTER PUBLICATION supabase_realtime ADD TABLE %I.%I;', pt.schemaname, pt.tablename) AS q,
         pt.schemaname || '.' || pt.tablename AS k
    FROM pg_publication_tables pt
   WHERE pt.pubname = 'supabase_realtime'
),

identidad_replica AS (
  SELECT format('ALTER TABLE public.%I REPLICA IDENTITY FULL;', c.relname) AS q, c.relname::text AS k
    FROM pg_class c
   WHERE c.relnamespace = 'public'::regnamespace AND c.relkind = 'r' AND c.relreplident = 'f'
),

buckets AS (
  SELECT format('INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types) VALUES (%L, %L, %L, %L, %L) ON CONFLICT (id) DO NOTHING;',
                b.id, b.name, b.public, b.file_size_limit, b.allowed_mime_types) AS q, b.id AS k
    FROM storage.buckets b
)

SELECT orden, seccion, objetos, sql
  FROM (
    SELECT  1 AS orden, 'extensiones'         AS seccion, count(*) AS objetos, string_agg(q, (SELECT s FROM fin) ORDER BY k) AS sql FROM ext
    UNION ALL SELECT  2, 'tipos',              count(*), string_agg(q, (SELECT s FROM fin) ORDER BY k) FROM tipos
    UNION ALL SELECT  3, 'secuencias',         count(*), string_agg(q, (SELECT s FROM fin) ORDER BY k) FROM secuencias
    UNION ALL SELECT  4, 'tablas',             count(*), string_agg(q, (SELECT s FROM fin) ORDER BY k) FROM tablas
    UNION ALL SELECT  5, 'restricciones',      count(*), string_agg(q, (SELECT s FROM fin) ORDER BY k) FROM restricciones
    UNION ALL SELECT  6, 'funciones',          count(*), string_agg(q, (SELECT s FROM fin) ORDER BY k) FROM funciones
    UNION ALL SELECT  7, 'vistas',             count(*), string_agg(q, (SELECT s FROM fin) ORDER BY k) FROM vistas
    UNION ALL SELECT  8, 'claves_ajenas',      count(*), string_agg(q, (SELECT s FROM fin) ORDER BY k) FROM claves_ajenas
    UNION ALL SELECT  9, 'indices',            count(*), string_agg(q, (SELECT s FROM fin) ORDER BY k) FROM indices
    UNION ALL SELECT 10, 'disparadores',       count(*), string_agg(q, (SELECT s FROM fin) ORDER BY k) FROM disparadores
    UNION ALL SELECT 11, 'rls',                count(*), string_agg(q, (SELECT s FROM fin) ORDER BY k) FROM rls
    UNION ALL SELECT 12, 'politicas',          count(*), string_agg(q, (SELECT s FROM fin) ORDER BY k) FROM politicas
    UNION ALL SELECT 13, 'permisos_tablas',    count(*), string_agg(q, (SELECT s FROM fin) ORDER BY k) FROM permisos_tablas
    UNION ALL SELECT 14, 'permisos_funciones', count(*), string_agg(q, (SELECT s FROM fin) ORDER BY k) FROM permisos_funciones
    UNION ALL SELECT 15, 'tiempo_real',        count(*), string_agg(q, (SELECT s FROM fin) ORDER BY k) FROM tiempo_real
    UNION ALL SELECT 16, 'identidad_replica',  count(*), string_agg(q, (SELECT s FROM fin) ORDER BY k) FROM identidad_replica
    UNION ALL SELECT 17, 'buckets',            count(*), string_agg(q, (SELECT s FROM fin) ORDER BY k) FROM buckets
  ) s
 ORDER BY orden;
